config/routes.rb
MarketMonitor::Application.routes.draw do
  get "apis/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :apis, only: [:new, :create]

  root to: 'static_pages#home'

  match "/signup", to: 'users#new'
  match "/signin", to: 'sessions#new'
  match "/signout", to: 'sessions#destroy', via: :delete

  match "/enrollnewapi", to: 'apis#new'
  match "/apilist", to: 'apis#show'

  match "/marketsummaries", to: 'MarketItemSummaries#show'
  match "/marketsummaries/filter", to: 'MarketItemSummaries#filter', via: :get

  match "/apis/wallet_settings", to: 'Apis#wallet_settings'
  match "/apis/set_wallet", to: 'Apis#set_wallet'

  match "/home", to: 'static_pages#home'
  match "/help", to: 'static_pages#help'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Market Monitor", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                APIs <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Enroll new API", enrollnewapi_path %></li>
                <li><%= link_to "API List", apilist_path %></li>
                <li class="divider"></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Market <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Item Order Summaries", marketsummaries_path %></li>
              </ul>
            </li>
            <li><%= link_to "Edit Account", user_path(current_user) %><li>
            <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign In", signin_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>